"""initial operational schema

Revision ID: f76fcaa4b556
Revises: 
Create Date: 2026-07-28 18:01:28.910794
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f76fcaa4b556'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_email', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.String(length=200), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_email'), 'audit_logs', ['user_email'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.Enum('LOA', 'ANNEX', 'VOLUME', 'AMENDMENT', 'VETO', 'OTHER', name='documentkind'), nullable=False),
    sa.Column('official_url', sa.String(length=1500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'title', 'kind')
    )
    op.create_index(op.f('ix_documents_kind'), 'documents', ['kind'], unique=False)
    op.create_index(op.f('ix_documents_year'), 'documents', ['year'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processed_documents', sa.Integer(), nullable=False),
    sa.Column('processed_pages', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('configuration_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('filters_json', sa.Text(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_queries_public_id'), 'saved_queries', ['public_id'], unique=True)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('ingestion_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('pdf_page_number', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_errors_run_id'), 'ingestion_errors', ['run_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('pdf_page_number', sa.Integer(), nullable=False),
    sa.Column('printed_page_label', sa.String(length=50), nullable=True),
    sa.Column('printed_page_method', sa.String(length=50), nullable=True),
    sa.Column('printed_page_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('page_sha256', sa.String(length=64), nullable=False),
    sa.Column('extraction_method', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'pdf_page_number')
    )
    op.create_index(op.f('ix_pages_version_id'), 'pages', ['version_id'], unique=False)
    op.create_index('ix_pages_version_printed', 'pages', ['version_id', 'printed_page_label'], unique=False)
    op.create_table('budget_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('organization_code', sa.String(length=30), nullable=True),
    sa.Column('program_code', sa.String(length=30), nullable=True),
    sa.Column('action_code', sa.String(length=30), nullable=True),
    sa.Column('function_code', sa.String(length=30), nullable=True),
    sa.Column('subfunction_code', sa.String(length=30), nullable=True),
    sa.Column('original_value', sa.String(length=100), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=80), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('deduplication_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deduplication_key')
    )
    op.create_index(op.f('ix_budget_records_action_code'), 'budget_records', ['action_code'], unique=False)
    op.create_index(op.f('ix_budget_records_function_code'), 'budget_records', ['function_code'], unique=False)
    op.create_index(op.f('ix_budget_records_organization_code'), 'budget_records', ['organization_code'], unique=False)
    op.create_index(op.f('ix_budget_records_program_code'), 'budget_records', ['program_code'], unique=False)
    op.create_index(op.f('ix_budget_records_subfunction_code'), 'budget_records', ['subfunction_code'], unique=False)
    op.create_index(op.f('ix_budget_records_year'), 'budget_records', ['year'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('context_before', sa.Text(), nullable=False),
    sa.Column('context_after', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'order_index')
    )
    op.create_index(op.f('ix_chunks_page_id'), 'chunks', ['page_id'], unique=False)
    op.create_table('content_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=30), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'order_index')
    )
    op.create_index(op.f('ix_content_blocks_page_id'), 'content_blocks', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_blocks_page_id'), table_name='content_blocks')
    op.drop_table('content_blocks')
    op.drop_index(op.f('ix_chunks_page_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_budget_records_year'), table_name='budget_records')
    op.drop_index(op.f('ix_budget_records_subfunction_code'), table_name='budget_records')
    op.drop_index(op.f('ix_budget_records_program_code'), table_name='budget_records')
    op.drop_index(op.f('ix_budget_records_organization_code'), table_name='budget_records')
    op.drop_index(op.f('ix_budget_records_function_code'), table_name='budget_records')
    op.drop_index(op.f('ix_budget_records_action_code'), table_name='budget_records')
    op.drop_table('budget_records')
    op.drop_index('ix_pages_version_printed', table_name='pages')
    op.drop_index(op.f('ix_pages_version_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_ingestion_errors_run_id'), table_name='ingestion_errors')
    op.drop_table('ingestion_errors')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_saved_queries_public_id'), table_name='saved_queries')
    op.drop_table('saved_queries')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_documents_year'), table_name='documents')
    op.drop_index(op.f('ix_documents_kind'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_user_email'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
